# Generated by Django 6.0.4 on 2026-04-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_usercardprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercardprogress",
            name="times_reviewed",
            field=models.IntegerField(default=0),
        ),
    ]
