# Generated by Django 6.0.4 on 2026-04-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userflashcard"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserCardProgress",
        ),
    ]
